extern u64 gLinkHumanMirrorShieldDL_mesh_tex_01CB00_i8_i8[];
extern Vtx gLinkHumanMirrorShieldDL_mesh_gLinkHumanMirrorShieldDL_mesh_mesh_layer_Transparent_vtx_cull[8];
extern Vtx gLinkHumanMirrorShieldDL_mesh_gLinkHumanMirrorShieldDL_mesh_mesh_layer_Transparent_vtx_0[54];
extern Gfx gLinkHumanMirrorShieldDL_mesh_gLinkHumanMirrorShieldDL_mesh_mesh_layer_Transparent_tri_0[];
extern Gfx mat_gLinkHumanMirrorShieldDL_mesh_f3dlite_material_437_layerTransparent[];
extern Gfx gLinkHumanMirrorShieldDL_mesh[];
